{% set version = "2.0.0" %}

package:
  name: requests-file
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/requests-file/requests-file-{{ version }}.tar.gz
  sha256: 20c5931629c558fda566cacc10cfe2cd502433e628f568c34c80d96a0cc95972

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - requests >=1.0.0
    - six

test:
  imports:
    - requests_file

about:
  home: http://github.com/dashea/requests-file
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: File transport adapter for Requests

extra:
  recipe-maintainers:
    - ocefpaf
