{% set version = "1.5.1" %}

package:
  name: requests-file
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/requests-file/requests-file-{{ version }}.tar.gz
  sha256: 07d74208d3389d01c38ab89ef403af0cfec63957d53a0081d8eca738d0247d8e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - requests >=1.0.0
    - six

test:
  imports:
    - requests_file

about:
  home: http://github.com/dashea/requests-file
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: File transport adapter for Requests

extra:
  recipe-maintainers:
    - ocefpaf
